name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          token: ${{github.token}}
          repos: |-
            dycw/actions
            pre-commit/pre-commit-hooks
          sleep: 1
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pyright'
        uses: dycw/action-pyright@latest
        with:
          token: ${{github.token}}
          python-version: "3.14"
          resolution: highest
          prerelease: disallow
          with-requirements: script.py
  pytest:
    env:
      CI: "1"
    name: pytest (${{matrix.os}}, ${{matrix.python-version}},
      ${{matrix.resolution}})
    runs-on: ${{matrix.os}}
    steps:
      - name: Run 'pytest'
        uses: dycw/action-pytest@latest
        with:
          token: ${{github.token}}
          python-version: ${{matrix.python-version}}
          resolution: ${{matrix.resolution}}
          prerelease: disallow
          with-requirements: script.py
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - "3.14"
        resolution:
          - highest
          - lowest-direct
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
        with:
          token: ${{github.token}}
